name: Publish package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: SCConfigDB
      Project_Library_Name: SCConfigDB
      Project_Library_Path: SCConfigDB/SCConfigDB
      Build_Config: Release 

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Download NuGet dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build solution items
      run: msbuild $env:Solution_Name /p:Configuration=$env:Build_Config
    
    - name: Publish artifacts
      run: dotnet publish $env:Solution_Name -c $env:Build_Config /p:PublishProfile=FolderProfile.pubxml --no-build
    
    - name: Build library NuGet package
      run: dotnet pack $env:Project_Library_Path -c $env:Build_Config --no-build
      
    - name: Publish NuGet package on GitHub
      run: dotnet nuget push "$env:Project_Library_Path/bin/$env:Build_Config/SCConfigDB.0.1.0.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
