name: Publish package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: SCConfigDB
      Project_Library_Name: SCConfigDB
      Build_Config: Release 

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Download NuGet dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build solution items
      run: msbuild $env:Solution_Name /p:Configuration=$env:Build_Config
    
    - name: Publish artifacts
      run: dotnet publish $env:Solution_Name -c $env:Build_Config /p:PublishProfile=FolderProfile.pubxml --no-build

    - name: Build and publish NuGet package
      run: |
        cd $env:Solution_Name\$env:Project_Library_Name
        dotnet pack -c $env:Build_Config --include-symbols --include-source --no-build
        dotnet nuget push "bin\${{ env.Build_Config }}\*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
