name: Build and publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: SCConfigDB
      Project_Library_Name: SCConfigDB
      Build_Config: Release 

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Download NuGet dependencies
      run: dotnet restore $env:Solution_Name --source https://api.nuget.org/v3/index.json

    - name: Build solution items
      run: msbuild $env:Solution_Name /p:Configuration=$env:Build_Config
    
    - name: Publish artifacts
      run: dotnet publish $env:Solution_Name -c $env:Build_Config /p:PublishProfile=FolderProfile.pubxml --no-build

    - name: Pack NuGet package
      working-directory: $env:Solution_Name\$env:Project_Library_Name
      run: dotnet pack -c $env:Build_Config --no-build

    - name: Publish NuGet package
      working-directory: $env:Solution_Name\$env:Project_Library_Name
      run: dotnet nuget push "bin\${{ env.Build_Config }}\*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"

    - name: Publish NuGet symbol package
      working-directory: $env:Solution_Name\$env:Project_Library_Name
      run: dotnet nuget push "bin\${{ env.Build_Config }}\*.snupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
